### ISSUE TITLE
DE analysis

### ISSUE THREAD

**Issue by mvis1231** [jianhuupenn/ItClust#11]
Hi,

I am following your tutorial, and I was wondering how to do differential expression analysis on the test data after generating tSNE plot (the end of your code).
Could you provide a brief code for this?

Thank you!!

**Comment by jianhuupenn** [comment]
You can directly use the rank_genes_groups() function in scanpy for DE.
For example:
```
sc.tl.rank_genes_groups(adata, groupby="label",reference="rest",n_genes=100, method='wilcoxon')
```

**Comment by mvis1231** [comment]
Thank you very much for the quick response!

After running,
```
clf=ic.transfer_learning_clf()
clf.fit(adata_A, adata_B) # where adata_A was used as training data and adata_B as a test data
```

(1) There was no "label" column created in my adata_B.obs (only "n_counts" column was added).
Should I manually copy "decisy_trans_True" column from clf.adata_test to adata_B.obs?

(2) Also, after running the code above, adata_B.X seems to have negative values. I think we should not have negative values in sc.tl.rank_genes_groups(). (please correct me if I am wrong here)
Should I run sc.tl.rank_genes_groups() before running the code above (clf.fit())? 

I appreciate your response!!

**Comment by jianhuupenn** [comment]
(1) You can add the label column manually, for example:
```
pred, prob, cell_type_pred=clf.predict()
adata.obs["label"]=pred
```
(2) The negative value is due to some preprocessing steps in ItClust, ItClust will take log and do the normalization. I would recommend reading the raw data again and do the DE, that is,
```
raw = sc.read("path_to_raw_data")
raw.var_names_make_unique()
raw.X=(raw.X.A if issparse(raw.X) else raw.X)
raw.raw=raw
sc.pp.log1p(raw)
#Add label column
raw.obs["label"]=pred
```
Then, do DE using raw.

Thanks,
Jian

**Comment by jianhuupenn** [comment]
No. We didn't do that.

**Comment by jianhuupenn** [comment]
I believe this is an issue in scanpy, not ItClust. I recommend you to read scanpy's tutorial.
