### ISSUE TITLE
TypeError: can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by wzqwtt** [jianhuupenn/ItClust#12]
I follow the tutorials:
[https://github.com/jianhuupenn/ItClust/blob/master/tutorial/tutorial.ipynb](https://github.com/jianhuupenn/ItClust/blob/master/tutorial/tutorial.ipynb)

However, I got some errors:
```python
pred, prob, cell_type_pred=clf.predict()
pred.head()
```
error : 
```
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_33548/453791501.py in <module>
      6 clf.fit(adata_train, adata_test)
      7 
----> 8 pred, prob, cell_type_pred=clf.predict()
      9 pred.head()
     10 

D:\ProgramData\Anaconda3\envs\ItClust\lib\site-packages\ItClust\ItClust.py in predict(self, save_dir, write)
    208             f=open(save_dir+"/celltype_assignment.txt","w")
    209             for k, v in celltype_pred.items():
--> 210                 f.write("Cluster "+str(k)+" is "+str(v[1]*100)+"%"+" to be "+v[0]+" cell\n")
    211 
    212             f.close()

TypeError: can only concatenate str (not "bytes") to str
```
Could you help with this problem ?

Thanks !

**Comment by jianhuupenn** [comment]
Hi lesileqin,
It's my first time seeing this error. Are you analyzing the toy data I provided or your own data?
Thanks.

**Comment by jianhuupenn** [comment]
Since we are running the same code in clf.predict(), no surprise to see the same error.
Could you print the "celltype_pred"? I think the error comes from it. Thx
