### ISSUE TITLE
When combined dataset is used as train or test data

### ISSUE THREAD

**Issue by mvis1231** [jianhuupenn/ItClust#14]
Happy new year!

I have a question about using a combined dataset as train or test data.

I have 4 datasets from different time points, and I previously integrate them using CarDEC. And now I want to use it as train data, and I have another integrated dataset from a different experiment that I will use for train data.
I am having following questions to this this.

(1) In my understanding, no matter what the data were previously integrated, ItClust will just use a combined dataset which is just a simply row-binded dataset of raw counts, right? 
(2) Do I need to have the dataset IDs in metadata?
(3) Do I need to put a parameter in a function to get rid of batch effects from the plainly combined datasets?
(4) Do the questions above depend on whether I use the combined dataset as train or test data in ItClust? (i.e. should the combined train data and the combined test data be treated differently?)

Thank you for your answer!

**Comment by jianhuupenn** [comment]
Hello,
Thank you for your interest in ItClust. Here are my suggestions for combing multiple datasets as training data:
- Before doing the combination, try to get a rough idea of the batch effect across these datasets. For example, you can make a tSNE plot, and see if cells from the same dataset stay together. If so, the batch effect is very strong and may need some correction.
- For batch effect removal, you can perform a simple normalization within each dataset or use some method like CarDEC.
- A bigger training dataset is not necessarily better than a smaller training dataset. I think the goal of combining multiple datasets is to make the training data contain more cell types. One example, dataset A have cell types {1,2,3}, B has {1,2}, C has {3,4,5,6}. So the combining strategy will be ignoring B and just combining datasets A and C. 

To answer your question:
1) ItClust just did the row-bind combination. But you can perform some batch effect remove steps before combining the data.
2) Not necessary, but recommended.
3) Please refer to my tips above
4) I don't have any experience in combining multiple datasets as testing data (not sure what is the benefit of this). I would recommend using acombined training dataset then predicting each test dataset separately.

Hope these suggestions are helpful.
Jian

**Comment by mvis1231** [comment]
Your suggestions are very helpful. Thank you for the prompt response!

I have a few following questions:

(1)
Let's say, I used Seurat to integrate the 4 datasets from different time points, and I want to use the integrated dataset as training data in ItClust.
In this case, instead of reading raw count matrix, I would need to read the normalized count for adata, like:
`adata = AnnData(mmread(os.path.join(path, "normalized_count.txt"))).T`
and then use it as training data?

(2) If I used CarDEC, instead of Seurat, should I use denoised counts for adata to be used for train data?

(3) The reason why I need to use an integrated dataset for testing data is that there were a few different mice used for the same experiment: for example, A data at 0 time point were from 2 mice and B data at 0 time point was from 1 mouse. Since both A and B data were at 0 time point but from different batches, I need to integrate them to combine the two datasets and also get rid of possible batch effects. Thus, I cannot use each dataset separately.
In this case, should I also read the normalized counts (or denoised counts from CarDEC) for this adata to be used as test dataset?

**Comment by jianhuupenn** [comment]
My answer to the first 2 questions is yes. Just make sure you do not take the log transformation twice.

For your third question, I would suggest you do the normalization within each dataset, then combine them, and use the normalized counts as input. ItClust has one inherent step for normalization, but normalizing twice does not hurt anything.

**Comment by mvis1231** [comment]
Thanks so much for your comments, Jian!

(1) Just to make sure on the log-transformation in your comment, you kindly warned me because I should not take the log-transformation twice when I do DE analysis? 
If it's not for DE analysis, was there any other step that I need to be aware of taking log-transformation?

(2) Regarding your last question, you meant I should normalize individual datasets separately, combine them, **normalize the combined dataset once again**, and then use this normalized dataset as input, right?

**Comment by jianhuupenn** [comment]
1) Usually I perform ALL the analysis on the log-transformation scale. That is log(UMI count+1).
2) There is no standard answer. I would normalize individual datasets separately, combine them, and start my analysis.

**Comment by mvis1231** [comment]
Thank you!!

I have started running clf.fit(train, test), and it seems like the code itself includes sc.pp.log1p and sc.pp.scale.

Do you think these functions kind of remove some batch effects between the samples in the testing data?

**Comment by mvis1231** [comment]
Thank you!!

One quick clarification!

In your paper (Combined source data, page7), you guys combined the reduced Baron et al. human data with the Xin et al. data and used it as a combined training data.
During the process, did you guys just simply row-combine the raw counts from the two datasets and used the combined dataset as training data? Or, did you guys used a combined normalized count after normalizing the two datasets separately?

**Comment by mvis1231** [comment]
What's the difference between "X_Embeded_z" value and "trajectory_Embeded_z" value obtained from clf.fit()??

**Comment by jianhuupenn** [comment]
"trajectory_Embeded_z" is used for evaluation and debugging. You can ignore it and use "X_Embeded_z" as the final embeddings.
