### ISSUE TITLE
Figure 5C in the paper

### ISSUE THREAD

**Issue by mvis1231** [jianhuupenn/ItClust#15]
Hi,

I have a question about figure 5C in your paper.

It was written that the four main cell types (alpha, beta, gamma and delta cells) were excluded from the source data, and Fig. 5C shows the main cells in the target data were predicted as "Pred_alpha", "Pred_beta", and etc. 

However, I thought that ItClust only used the cell type labels from a source data, so for example, if we have 5 cell types labeled in the source data, then ItClust gives us 5 cell types (i.e. 5 clusters) in the target data (Correct?)

Then, how did you guys get the labels "Pred_alpha", "Pred_beta", "Pred_gamma", "Pred_delta" as shown in the Sankey plot, even though the source data did not include those labels.

Thanks for your help!

**Comment by jianhuupenn** [comment]
Hi there,

We identified the clusters to be novel/unseen cell types based on the low confidence scores and then assigned cell types by looking at DE genes. Please refer to our paper for details.

**Comment by mvis1231** [comment]
Thanks!

What range of confidence score did you guys consider as low?? i.e. less than 30%?
Also, what range of confidence score should be interpreted as high?

**Comment by jianhuupenn** [comment]
It depends on the batch effects between source and target. For example, 4 clusters:
If 90%, 90%, 90%, 70%, then the 70% one may be a novel cell type or the same cell type but at different cell stage.
If 70%, 70%, 70%, 40%, then the 40% one may be low one.

**Comment by mvis1231** [comment]
I see. It's more relative.

About your 2nd example, 70%, 70%, 70%, 40%, do you consider 70% is still a good percentage? 
I know that it is higher than 40% so it is better than the 4th cluster relatively, but I was also wondering what percentage we should consider as reliable. Any absolute scale that we can refer to?

**Comment by jianhuupenn** [comment]
I think there is no absolute value. In my experience, it highly depends on the cell types and their relationships. For example, if you are separating very distinct cell types, like alpha, beta, gamma cells, the confidence score will be very high(>90%). When you are separating the cell types that are very close, or have the same precursor, like immune cell types, macrophage and fibroblast, different subtypes of T cells, the scores will overall be low. This also indicates these cells are biologically similar.

**Comment by mvis1231** [comment]
Your detailed description is very helpful and informative! Thanks so much!!
