### ISSUE TITLE
QUESTION: How to predict on `anndata` object?

### ISSUE THREAD

**Issue by cartal** [jianhuupenn/ItClust#3]
Hi, 

From your tutorial, the prediction step says that you have to do: 

```
pred, prob, cell_type_pred=clf.predict()
pred.head()
```

Perhaps I'm missing something, but how do you use this model if you want to predict cell types on another dataset as a `anndata` object, similar to the ones you used to train the model?

Thanks in advance for the help!

**Comment by jianhuupenn** [comment]
Hi Cartal,
ItClust model uses training data to train the model and then uses testing data for fine-tunning. Therefore, both training and testing data are feed to the model in the training step, no input needed for the predicting step. As you can see from the tutorial:
clf=ic.transfer_learning_clf()
clf.fit(adata_train, adata_test) # Input training and testing data into the model simultaneously.
pred, prob, cell_type_pred=clf.predict() # No more input for predicting.
If you want predict multiple testing data, I recommend you to train a new model.

Jian

**Comment by cartal** [comment]
Thanks for the quick reply! 

I'm trying to transfer the labels from the `training` dataset to the `test` dataset. What I do is that I load the `training` dataset and I add `training.obs["cell type"]` for the ground truth labels, as indicated in the tutorial. However, when I run:

```
clf.fit(training, test, epochs_fit = 100)
```

It fails with this error: 

```
/opt/conda/lib/python3.7/site-packages/scanpy/preprocessing/_simple.py:297: DeprecationWarning: Use is_view instead of isview, isview will be removed in the future.
  if isinstance(data, AnnData) and data.isview:
the var_names of adata.raw: adata.raw.var_names.is_unique=: True
/opt/conda/lib/python3.7/site-packages/scanpy/preprocessing/_simple.py:297: DeprecationWarning: Use is_view instead of isview, isview will be removed in the future.
  if isinstance(data, AnnData) and data.isview:
/opt/conda/lib/python3.7/site-packages/scanpy/_utils.py:341: DeprecationWarning: Use is_view instead of isview, isview will be removed in the future.
  if adata.isview:
/opt/conda/lib/python3.7/site-packages/scanpy/preprocessing/_simple.py:297: DeprecationWarning: Use is_view instead of isview, isview will be removed in the future.
  if isinstance(data, AnnData) and data.isview:
the var_names of adata.raw: adata.raw.var_names.is_unique=: True
/opt/conda/lib/python3.7/site-packages/scanpy/preprocessing/_simple.py:297: DeprecationWarning: Use is_view instead of isview, isview will be removed in the future.
  if isinstance(data, AnnData) and data.isview:
/opt/conda/lib/python3.7/site-packages/scanpy/_utils.py:341: DeprecationWarning: Use is_view instead of isview, isview will be removed in the future.
  if adata.isview:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2889             try:
-> 2890                 return self._engine.get_loc(key)
   2891             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'celltype'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-15-d9f36cb0abaf> in <module>
----> 1 clf.fit(training, test, epochs_fit = 100)

/opt/conda/lib/python3.7/site-packages/ItClust/ItClust.py in fit(***failed resolving arguments***)
    122             x_train=adata_train.X
    123 
--> 124         y_train=pd.Series(adata_train.obs["celltype"],dtype="category")
    125         y_train=y_train.cat.rename_categories(range(len(y_train.cat.categories)))
    126         print("The number of training celltypes is: ", len(set(y_train)))

/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2973             if self.columns.nlevels > 1:
   2974                 return self._getitem_multilevel(key)
-> 2975             indexer = self.columns.get_loc(key)
   2976             if is_integer(indexer):
   2977                 indexer = [indexer]

/opt/conda/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2890                 return self._engine.get_loc(key)
   2891             except KeyError:
-> 2892                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2893         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2894         if indexer.ndim > 1 or indexer.size > 1:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'celltype'
```

However, when I use `training.obs["celltype"]` without any space, it works without any errors, but instead it gives me table with the _cell ids_ and _clusters_, where the clusters are numbers and not the labels in `training.obs["celltype"]`. 

Do you know what I may be doing wrong?

**Comment by jianhuupenn** [comment]
Hi Cartal,
You should used training.obs["celltype"] instead of training.obs["cell type"]. And for your second question, the output is correct. ItClust will give you the raw clustering results. In order to label each cluster, you should looked at the celltype_assigment.txt file generated by ItClust. Please refer to the tutorial for details:

predict() function will return the cluster prediction, clustering probability matrix and cell type confidence score.
If the parameter write==True(default), it will also write the results to save_dir.
The cluster prediction is written to save_dir+"/clustering_results.csv".
The cell type confidence score is written to save_dir+"/cell type_assignment.txt".
The clustering probability matrix is written to save_dir+"/clustering_prob.csv".

Jian

**Comment by cartal** [comment]
Fantastic! Thanks so much! 

Regards
