### ISSUE TITLE
how to interpret "Cluster X is 0% to be Y cell"

### ISSUE THREAD

**Issue by qingnanl** [jianhuupenn/ItClust#4]
Hi authors,

Great package. I just have one question. WIth my prediction with default parameters, it gives me this result (celltype_assignment.txt).

Cluster 0 is 100.0% to be a cell
Cluster 1 is 83.1% to be b cell
Cluster 2 is 99.8% to be c cell
Cluster 3 is 93.10000000000001% to be d cell
Cluster 4 is 56.49999999999999% to be e cell
Cluster 5 is 95.8% to be f cell
Cluster 6 is 95.89999999999999% to be g cell
Cluster 7 is 95.8% to be h cell
Cluster 8 is 96.8% to be i cell
Cluster 9 is 0.3% to be j cell
Cluster 10 is 0.0% to be k cell
Cluster 11 is 0.0% to be l cell
Cluster 12 is 4.3999999999999995% to be m cell
Cluster 13 is 0.0% to be n cell
Cluster 14 is 0.0% to be o cell
Cluster 15 is 0.0% to be p cell
Cluster 16 is 0.0% to be q cell
Cluster 17 is 0.0% to be r cell
...

How should I interpret this result?

Thanks!

**Comment by jianhuupenn** [comment]
Hi qingnanl,
For clusters with high confidence scores, such as 0, 2, 3 in your case, they tend to have a higher possibility to be the same type as they referred to.
For clusters with medium score, such as 4, it may be a different but similar cell type of e. For example, when analyzing immune cells, e and cluster 4 may be different T cell subtypes. 
For clusters with scores close to 0, they may belong to some novel cell types that are not presented in your training data. 

Hope this helps!
Jian

**Comment by qingnanl** [comment]
> Hi qingnanl,
> For clusters with high confidence scores, such as 0, 2, 3 in your case, they tend to have a higher possibility to be the same type as they referred to.
> For clusters with medium score, such as 4, it may be a different but similar cell type of e. For example, when analyzing immune cells, e and cluster 4 may be different T cell subtypes.
> For clusters with scores close to 0, they may belong to some novel cell types that are not presented in your training data.
> 
> Hope this helps!
> Jian

Hi Jian,

Thanks. Another question, since I do have a quite complex dataset (over 30 cell types), what parameter should I consider to tune.

Best,

qingnan

**Comment by jianhuupenn** [comment]
There are many many hyper parameters in ItClust, such as network structure. You don't need to tune them since ItClust will automatically select suitable parameters based on the data, which I think to be one advantage of ItClust. If you want ItClust to learn different information, you can try different training data, or simply modify the training data(e.g., combine some similar cell types as one) based on your purpose.
